# Use this in your UnturnedImages/config.yaml file
- Id: "7777" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2153272553/vehicles/{ItemId}.png" # The repository of the override.